budimanjojo/talhelper

example/talconfig.yaml, pkg/config/validate/config.go, pkg/config/validate/validator.go, pkg/config/validate/validator_test.go
=> feat(config): improve version validation

example/talconfig.yaml, pkg/config/config.go, pkg/talos/nodeconfig.go
This PR adds support for specifying machineDisks on the node level
=> feat: Add support for specifying machineDisks

cmd/genurl_installer.go, cmd/genurl_iso.go
Fixes: https://github.com/budimanjojo/talhelper/issues/211
=> feat(genurl): generate url with context of `talconfig.yaml`

cmd/gencommand_upgrade-k8s.go, pkg/generate/command.go
Fixes: https://github.com/budimanjojo/talhelper/issues/227
=> feat(gencommand): add upgrade-k8s subcommand

pkg/substitute/envsubst.go, pkg/substitute/testdata/file1.yml, pkg/substitute/testdata/file2.yaml
Fixes: https://github.com/budimanjojo/talhelper/issues/220
=> fix(substitute): fix issue parsing env file with yaml document delimiter

.github/workflows/docker-build-and-push.yaml, Dockerfile
=> feat: Create Docker Image

.devcontainer/devcontainer.json
I have been using this devcontainer image to work on some of the features I've been proposing lately. Thought I'd drop this here in case you find it useful.
I think it can help streamline the dev environment as well as help potential contributors get a dev env up and running quickly.
Feel free to close this if you're not interested!
=> feat: Add devcontainer configuration

pkg/config/validate.go, pkg/config/validator.go
Fixes: https://github.com/budimanjojo/talhelper/issues/326
=> feat(validate): improve validation for supported Talos version

cmd/gencommand_reset.go
=> Fix Reset typo

cmd/gencommand_kubeconfig.go, pkg/generate/command.go
Fixes: https://github.com/budimanjojo/talhelper/issues/339
=> feat(gencommand): add kubeconfig command

pkg/talos/talosconfig.go
Fixes: https://github.com/budimanjojo/talhelper/issues/347
=> feat(genconfig): put all nodes in `nodes` inside `talosconfig`

cmd/genconfig.go, cmd/root.go, cmd/validate_talconfig.go, pkg/config/loader.go, pkg/config/validate.go, pkg/decrypt/decrypt.go, pkg/generate/config.go, pkg/substitute/envsubst.go, pkg/talos/input.go, pkg/talos/nodeconfig.go, pkg/talos/schematic.go, pkg/talos/talosconfig.go
Fixes: https://github.com/budimanjojo/talhelper/issues/356
=> feat: add --debug flag

example/talconfig.yaml, example/talenv.yaml, example/tsauth.env, pkg/config/loader.go
Fixes: https://github.com/budimanjojo/talhelper/issues/393
=> feat(config): allow providing local file for `machineFiles`

pkg/patcher/patcher.go, pkg/patcher/patcher_test.go, pkg/patcher/testdata/encrypted.sops.yaml
This PR adds supports for encrypted patch file, so that users can easily commit their patches containing some sensitive information.
=> feat(config): Supports encrypted patch file

docs/docs/reference/configuration.md, example/talconfig.yaml, pkg/config/config.go, pkg/generate/config.go, pkg/talos/extensionserviceconfig.go, pkg/talos/extensionserviceconfig_test.go
This allows creating additional files to be applied to configure extension services configuration.
More information: https://www.talos.dev/v1.7/introduction/what-is-new/#extension-services-configuration
=> feat(config): support `system extensions` config file

pkg/talos/input.go
=> fix: secretfile is empty

cmd/genurl_installer.go
Fixes: https://github.com/budimanjojo/talhelper/issues/480
=> fix(genurl_installer): use provided installer url if specified

.github/workflows/release.yaml
=> ci: Add dry-run flag to goreleaser

cmd/validate_talconfig.go
Fixes: https://github.com/budimanjojo/talhelper/issues/837
=> feat(validate_talconfig): exit with code 1 when issues found

README.md
=> docs: update to home-operations

docs/docs/reference/configuration.md, pkg/config/config.go, pkg/config/defaults.go, pkg/config/gitignore.go, pkg/config/outputfilename.go, pkg/config/outputfilename_test.go, pkg/generate/command.go, pkg/generate/config.go
Fixes: https://github.com/budimanjojo/talhelper/issues/979
- **feat(genconfig): support changing the output file name**
- **docs(reference): update docs**
=> feat(genconfig): support changing the output file name

pkg/talos/input.go
Fixes: https://github.com/budimanjojo/talhelper/issues/926
=> feat(genconfig): verbose warning instead when secrets file is not found

docs/docs/guides.md
Some minor tweaks to the guide.
=> tweaked documentation a bit

docs/docs/guides.md, pkg/generate/config.go, pkg/templating/template.go
Fixes: https://github.com/budimanjojo/talhelper/issues/1012
=> feat(config): allow go template inside `extraManifests` files

docs/docs/reference/configuration.md, example/talconfig.yaml, pkg/config/config.go, pkg/talos/uservolumeconfig.go, pkg/talos/uservolumeconfig_test.go
Fixes: https://github.com/budimanjojo/talhelper/issues/1096
=> feat(config): add `encryption` field for `userVolumes`

docs/docs/reference/configuration.md, pkg/config/config.go, pkg/talos/volumeconfig.go
Fixes: https://github.com/budimanjojo/talhelper/issues/1147
=> feat(config): add `encryptionSpec` to `volumes`

cmd/gencommand_health.go, pkg/generate/command.go
Hi!
we are increasingly using Talhelper to build our talos clusters and I was missing a way to generate the health command and I didn't wanna do it by hand. 
So I made this. Might be a bit rough around the edges. If you want me to conform to the other Generate commands, just let me know and I will change the functionality!
Kind Regards
Yannick
Signed-off-by: Yannick Wahner <thenabsku@gmail.com>
=> Added Health Check Generation
