budimanjojo/talhelper

.goreleaser.yaml

Adding a windows build to each release seems quite easy and itwould make working with our talos clusters from a Windows machine a bit easier. I tested it on my machine and seems to work great!

Add windows-amd64 build

---

.goreleaser.yaml
README.md

This PR uses a [Gorelease feature](https://goreleaser.com/customization/scoop/?h=scoop) to create a scoop manifest after release. Once merged and after the first release, one can install talhelper by running
```
scoop bucket add budimanjojo https://github.com/budimanjojo/talhelper.git
scoop install talhelper
```
As soon as the first Windows release is available as an asset, we can also try to get it added to the [Main scoop bucket](https://github.com/ScoopInstaller/Main/). But as it does not matches the [criteria](https://github.com/ScoopInstaller/Scoop/wiki/Criteria-for-including-apps-in-the-main-bucket) yet, we'll probably need to add it to the [Extras](https://github.com/ScoopInstaller/Extras) bucket where there's a big backlog of PRs and the steps to install it are not much different …

Add embedded Scoop manifest

---

docs/docs/reference/configuration.md
example/talconfig.yaml
pkg/config/config.go
pkg/config/loader.go
pkg/config/loader_test.go
pkg/config/testdata/env1.yaml
pkg/config/testdata/env2.yml
pkg/config/testdata/talconfig.yaml

The schematic can be applied to all nodes based on their types. But it will prioritize `node[].schematic` if specified.
Fixes: https://github.com/budimanjojo/talhelper/issues/217

feat(config): add controlplane and worker schematic

---

cmd/gencommand_bootstrap.go
pkg/generate/command.go

If no `--node` flag is provided, will use the first controlplane node. If the provided flag is not a controlplane node, will return error and exit 1
Fixes: https://github.com/budimanjojo/talhelper/issues/223

feat(gencommand): add bootstrap subcommand

---

cmd/gencommand_upgrade.go
cmd/genconfig.go
cmd/genurl_installer.go
cmd/genurl_iso.go
docs/docs/reference/configuration.md
pkg/config/config.go
pkg/config/defaults.go
pkg/generate/command.go
pkg/generate/config.go
pkg/talos/nodeconfig.go
pkg/talos/nodeconfig_test.go
pkg/talos/schematic.go
pkg/talos/schematic_test.go

Fixes: https://github.com/budimanjojo/talhelper/issues/232
Because the image-factory server needs to know the requested schematic
id in order to be able to provide the image and ISO, we should do a HTTP
POST request to the server.
This will impact on the talhelper needing internet connection to work,
and this also mean it will prone to failure in case the server is down
or we can not establish connection with the image factory server.
So there's `--offline-mode` flag (disabled by default) added to some
commands to overcome this.

feat: use HTTP POST request to generate schematic id

---

cmd/genurl_iso.go
docs/docs/reference/configuration.md
pkg/config/config.go
pkg/config/defaults.go
pkg/talos/schematic.go

This adds per node `machineSpec` that will be used to get ISO image URL
from the registry. For example, you can have a node like this:
```
nodes:
- hostname: node1
machineSpec:
mode: metal
arch: arm64
```
Doing `talhelper genurl iso` from the directory where talconfig.yaml is
found will generate the url to download ISO image for that node.

Improve `genurl iso` subcommand

---

pkg/talos/nodeconfig.go
pkg/talos/nodeconfig_test.go

It makes more sense because you should expect them to be loaded if you
define schematic that has them. By default installer image ignores
kernel args so they will not be loaded unless you define them in your
machine configs at `machine.install.extraKernelArgs`.
Ref: https://www.talos.dev/v1.5/learn-more/image-factory/#restrictions
Fixes: https://github.com/budimanjojo/talhelper/issues/243

feat(genconfig): add extraKernelArgs to machine.install.extraKernelArgs

---

.github/workflows/docker-build-and-push.yaml

These 2 renovate PRs are upgrading the upload/download-artifact action from v3 to v4:
- https://github.com/budimanjojo/talhelper/commit/24c6431bf5f47b570991a23b8e50068cdadd6653
- https://github.com/budimanjojo/talhelper/commit/3a05d6304036c8d28d0149bd3cab57fd3bee4aa0
And there are breaking changes for v4: https://github.com/actions/upload-artifact#breaking-changes
This PR fixes the issues (and does a tiny bit of cleanup on the workflow file as well).
Successful job: https://github.com/mirceanton/talhelper/actions/runs/7247675983/job/19742395789

fix(ci): Fix docker build workflow

---

hack/tsehelper/tags.go
hack/tsehelper/tar_archive.go

This PR fixes the parsing of the Docker manifest by searching for the file named `image-digests` and parsing that specifically.

Fix parsing of image-digests from docker manifest

---

docs/docs/reference/configuration.md
example/talconfig.yaml
pkg/config/config.go
pkg/config/schema.go
pkg/config/validate.go
pkg/config/validate_test.go
pkg/config/validator.go
pkg/generate/config.go
pkg/talos/networkconfig.go
pkg/talos/networkconfig_test.go

Fixes: https://github.com/budimanjojo/talhelper/issues/284
This allows you to have something like this in your `talconfig.yaml`:
```
nodes:
- firewallSpec:
ingress:
defaultAction: block
rules:
- name: kubelet-ingress
portSelector:
ports:
- 10250
protocol: tcp
ingress:
- subnet: 172.20.0.0/24
except: 172.20.0.1/32
```
And it will then create something like this appended in the generated
manifest for the node that you can apply using `talosctl`:
```
apiVersion: v1alpha1
kind: NetworkDefaultActionConfig
ingress: block
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: kubelet-ingress
portSelector:
ports:
- 10250
protocol: tcp
ingress:
- subnet: 172.20.0.0/24
except: 172.20.0.1/32
```
Ref: https://www.talos.dev/v1.6/talos-guides/network/ingress-firewall/

feat(config): supports firewall configuration for nodes

---

docs/docs/reference/configuration.md
pkg/config/config.go
pkg/config/validate.go
pkg/config/validate_test.go
pkg/config/validator.go
pkg/generate/config.go
pkg/talos/networkconfig.go

Fixes: https://github.com/budimanjojo/talhelper/issues/291
This allows you to have something like this in your `talconfig.yaml`:
```yaml
nodes:
- extraManifests:
- etcd-firewall.yaml
- kubelet-firewall.yaml
- ../anotherfile.yaml
```
And the content of those files will be appended in the generated
manifest for the node that you can apply using `talosctl` like so:
```yaml
<generated machineconfig>
---
<etcd-firewall.yaml content>
---
<kubelet-firewall.yaml content>
---
<../anotherfile.yaml content>
```
This is made to prepare for
https://github.com/siderolabs/talos/issues/7223

feat(config): supports extra manifests for nodes

---

docs/docs/reference/configuration.md
example/talconfig.yaml
pkg/config/config.go
pkg/config/validate_test.go
pkg/config/validator.go
pkg/generate/config.go
pkg/talos/networkconfig.go
pkg/talos/networkconfig_test.go

This lets you add `ingressFirewall` and `extraManifests` to all
controlplane or worker nodes too
Ref: https://github.com/budimanjojo/talhelper/issues/284

feat(config): add node groups `ingressFirewall` and `extraManifests`

---

pkg/generate/command.go

Fixes: https://github.com/budimanjojo/talhelper/issues/304

fix(gencommand): `gencommand upgrade` should respect `talosImageURL`

---

docs/docs/guides.md
docs/docs/reference/configuration.md
pkg/config/config.go
pkg/config/defaults.go
pkg/config/loader.go
pkg/config/loader_test.go
pkg/config/nodeconfigs.go
pkg/config/nodeconfigs_test.go
pkg/config/testdata/talconfig.yaml
pkg/config/validate.go
pkg/config/validate_test.go
pkg/config/validator.go
pkg/generate/config.go
pkg/talos/input.go
pkg/talos/nodeconfig.go
pkg/talos/nodeconfig_test.go

This will allow all `NodeConfigs` fields to be applicable on node group
(`controlPlane` or `worker` depending on node type) or per node level.
The config will be "merged" with everything defined on per node level
take precedence, except for `patches` and `extraManifests` to keep the
behavior before this commit. Patches and extaManifests defined on both
node and node group level will be appended instead.
There are 2 new node options to change the behavior of `patches` and
`extraManifests` when defined at both the node and node group level.
Which are: `overridePatches` and `overrideExtraManifests`. By setting
them to `true` will make the `patches` and `extraManifests` defined in
node level to override the ones defined in node group level.
The config validation is now done after the …

feat(config)!: `controlPlane` and `worker` is now type of `NodeConfigs`

---

cmd/genurl.go
cmd/genurl_installer.go
cmd/genurl_iso.go
docs/docs/reference/configuration.md
example/talconfig.yaml
pkg/config/config.go
pkg/config/defaults.go
pkg/generate/command.go
pkg/talos/nodeconfig.go
pkg/talos/schematic.go
pkg/talos/schematic_test.go

Ref: https://github.com/budimanjojo/talhelper/issues/304
This allows generating per node secureboot installer and ISO url.
You can have per node `machineSpec` like so:
```yaml
---
nodes:
- machineSpec:
secureboot: true
```
And the generated installer url will be something like:
`factory.talos.dev/installer-secureboot/<hash>:v1.6.0`

feat(config): support secureboot installer and ISO url

---

cmd/genurl_iso.go
docs/docs/guides.md
docs/docs/reference/configuration.md
pkg/config/config.go
pkg/config/defaults.go
pkg/config/validator.go
pkg/generate/command.go
pkg/talos/nodeconfig.go
pkg/talos/talosconfig.go

Fixes: https://github.com/budimanjojo/talhelper/issues/344
This allows the generated configs to be applicable by many nodes, i.e you have similar hardware for all your nodes and let your DHCP server to handle the IP addresses and hostname for you.

Support generating single file for all nodes

---

pkg/config/nodeconfigs.go

Fixes: https://github.com/budimanjojo/talhelper/issues/388
Before this, the `patches` in `nodes[]` will get applied first, then the `patches` in `controlPlane` or `worker`.
This resulted in a scenario like this will not be possible:
```yaml
nodes:
- hostname: master
controlPlane: true
overridePatches: false
patches:
- |-
- op: add
path: /machine/kubelet/extraMounts/-
value:
destination: /var/mnt/tank
type: bind
options:
- bind
controlPlane:
patches:
- |-
- op: add
path: /machine/kubelet/extraMounts
value:
- destination: /var/lib/longhorn
options:
- bind
```
Your goal is to have `/machine/kubelet/extraMounts` of `master` node to have 2 items, while the other `controlPlane` nodes to have 1 item.
After this patch, this should now work fine.

feat(config): global patches should be applied first

---

.github/workflows/docker-build-and-push.yaml
Dockerfile

With this build arg we can inject extra flags to the `go build` command so that we can set up the `--version` flag for the binary distributed via docker.
Fixes #473

feat(docker): Add ability to inject build flags to the `go build` command

---

pkg/talos/networkconfig.go

Fixes: https://github.com/budimanjojo/talhelper/issues/497

fix(genconfig): don't include the provided doc delimiter if exists

---

go.mod
pkg/config/defaults.go
pkg/config/schemas/versiontags/versiontags.go
pkg/config/validator.go

This will make the main talhelper module `go get` able.
After I publish a new release with this PR merged, I will need to also update the code in `tsehelper` to use this type for DRY reason.
Fixes: https://github.com/budimanjojo/talhelper/issues/516

feat(code): make `versiontags` a type inside main go module

---

cmd/validate_talconfig.go
pkg/config/loader.go

Closes: https://github.com/budimanjojo/talhelper/issues/492
Although this doesn't completely do what the original issue is suggesting, but this looks like a better approach.
Users should look at the documentation before using this program.
This PR is not completely done yet.
Maybe docs also need improvement or maybe there are more error messages that needs to be linked to the related docs etc.

Link users to docs on errors

---

docs/docs/reference/configuration.md
pkg/config/config.go
pkg/config/validate.go

fixes: https://github.com/budimanjojo/talhelper/issues/537
The validation only works for official Talos image factory anyway so it makes more sense if we just don't do validation altogether for selfhosted image factory.

feat(validate): don't validate on selfhosted image factory

---

docs/docs/reference/configuration.md
example/talconfig.yaml
pkg/config/config.go
pkg/config/nodeconfigs_test.go
pkg/config/validate.go
pkg/config/validator.go
pkg/talos/nodeconfig.go

This add the ability to define node annotations in `talconfig.yaml` file.
Not sure how the `talosctl` will react to when the version is below Talos v1.8 because this feature is not available before this version.

feat(config): add support for `nodeAnnotations`

---

pkg/substitute/envsubst.go
pkg/substitute/envsubst_test.go

Hi, I was encountering a bug where an `inlineManifest` added via patch in my `talconfig.yaml` was ending up malformed in the node config generated by talhelper.
For example, my patch had this line:
```yaml
- '--log-format [%Y-%m-%d %T.%e][%t][%l][%n] [%g:%#] %v'
```
Which was being modified to:
```yaml
- '--log-format [%Y-%m-%d %T.%e][%t][%l][%n] [%g:
```
I tracked the issue down to the yaml comment stripping phase: the current regex is a bit overzealous and thought there was a comment in that string. Seeing the `// FIXME use better logic than regex` comment there, I thought I'd take a shot at improving it.
The approach I went with is a little heavyweight. The input is fully parsed into a yaml AST, operated on, and then re-rendered to bytes. This is probably best for correctness, but I …

Use full yaml parsing for more correct comment stripping

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.github/workflows/devcontainer-build.yaml

I noticed the devcontainer configuration was failing. There was apparently some issue with the `age` installer or something like that.
To be fully honest I never really liked those devcontainer features as they're too much of a black box and I don't have much visibility into how they're doing their thing. With this approach we just collect all of the binaries we need from official and trusted docker images to piece together a working config.

chore(devcontainer): Update configuration and add CI workflow

---

cmd/gencommand.go
cmd/genurl.go
cmd/helpers/completions.go

With this PR, you will now get shell completion for `--node` flag.
It will work even when you're not inside the directory where `talconfig.yaml` file exists by providing the `--config-file` and `env-file` flag.
Example scenarios:
You are in the directory where `talconfig.yaml` exists
* You type `talhelper gencommand upgrade --node` and press `Tab`.
* Your shell will provide list of hostnames and IP addresses that you define inside `talconfig.yaml`.
You are not in the directory where `talconfig.yaml` exists
* You type `talhelper gencommand upgrade -c anotherdir/talconfig.yaml --env-file anotherdir/talenv.yaml -n` and press Tab.
* Your shell will provide list of hostnames and IP addresses that you define inside `anotherdir/talconfig.yaml`.
But, nothing is perfect and there's a problem that …

feat(cmd): generate autocompletion for `--node` flag

---

pkg/config/loader.go
pkg/substitute/pathsubst.go
pkg/substitute/pathsubst_test.go

Really not sure what to call this PR :)))
Basically this is a very trivial PoC to validate that we can rewrite the relative paths in relation to the directory from which `talhelper` has been called given that we have the path to the config file in the `--config-file` flag.

fix: Add support for relative paths when called from another dir

---

pkg/generate/config.go
pkg/patcher/patcher.go
pkg/patcher/patcher_test.go

Fixes: https://github.com/budimanjojo/talhelper/issues/645

fix(genconfig): skip applying patch that contains empty file

---

docs/docs/installation.md
flake.nix

This PR adds an flake overlay for nix users to easily add talhelper into their own pkgs with an overlay 
For example in my nix dots:
```nix
nixosConfigurations = {
${user.hostname} = nixpkgs.lib.nixosSystem {
specialArgs = {
pkgs = import nixpkgs {
overlays = [
inputs.talhelper.overlays.default
];
inherit system;
config.allowUnfree = true;
};
inherit inputs system user;
};
```
now I have access to pkgs.talhelper where I want to use or install it at.

Add flake parts easy overlay for more idiomatic experience for nix users.

---

flake.nix

Fix. Mistakenly had default in the overlay which resulted in the package name being default so you would have to do pkgs.default to install talhelper instead of pkgs.talhelper. This fixes that.

fix(flake): Update package to be talhelper not default

---

cmd/genurl_iso.go
docs/docs/reference/configuration.md
pkg/config/config.go

This allows having different image for ISO and installer
Fixes: https://github.com/budimanjojo/talhelper/issues/676

feat(config): add `isoSchematic` for `genurl iso` if defined

---

docs/docs/reference/configuration.md
example/talconfig.yaml
pkg/config/config.go
pkg/generate/config.go
pkg/talos/volumeconfig.go
pkg/talos/volumeconfig_test.go

Fixes: https://github.com/budimanjojo/talhelper/issues/781

feat(config): add `volumes` field for `VolumeConfig` manifest

---

cmd/genurl_image.go
docs/docs/reference/configuration.md
pkg/config/config.go
pkg/config/defaults.go
pkg/config/validate.go
pkg/config/validator.go
pkg/talos/schematic.go

Fixes: https://github.com/budimanjojo/talhelper/issues/790
BREAKING CHANGE: Before this change, `talhelper genurl iso` will generate this:
`https://factory.talos.dev/image/<id>/<version>/<mode>-<arch>.iso`
Now you can do the same with `talhelper genurl image`
In addition to ISO images, you can also generate disk and PXE images.
For example, to generate disk-image with default raw.zst extension you can do:
`talhelper genurl image --boot-method disk-image`
and it will output:
`https://factory.talos.dev/image/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba/v1.9.1/metal-amd64.raw.zst`
If you want to generate url for node inside `talconfig.yaml` you can have something like this (i.e for Pine64 SBC):
```yaml
nodes:
- hostname: kmaster1
schematics:
customization: {}
overlay: …
```

feat(genurl)!: replace `genurl iso` subcommand with `genurl image`

---

docs/docs/reference/configuration.md
pkg/config/config.go
pkg/config/loader.go
pkg/config/validate.go
pkg/config/validator.go
pkg/config/wrapper.go
pkg/generate/config.go
pkg/substitute/contentsubst.go
pkg/substitute/contentsubst_test.go
pkg/substitute/pathsubst.go
pkg/substitute/testdata/content.yaml
pkg/talos/nodeconfig.go

Fixes: https://github.com/budimanjojo/talhelper/issues/833
- **feat(config): allow `machineFiles` to be not envsubst-ed**
Now, you can have something like this so the content is not being env
substituted by `talhelper`:
```yaml
nodes:
- machineFiles:
- content: "@./a-file-outside-of-config"
permission: 0o644
path: /path/inside/node
op: create
skipEnvsubst: true
```
Note that this only works for file outside of `talconfig.yaml` like
shown in the example above because `talhelper` will do envsubst to the
entire config file and there's no easy way to change that.
- **feat(config): add `inlineManifests`**
Just like `machineFiles`, you can tell `talhelper` to skip env
substituting the content of the manifest like so:
```yaml
inlineManifests:
- name: cilium
contents: …
```

add `inlineManifests` and add feature to `machineFiles`

---

.devcontainer/Dockerfile

This PR swaps the kubectl binary from bitnami/kubectl to registry.k8s.io/kubectl, also updates the binary copy location.

Swap kubectl Install Image

---

docs/docs/reference/configuration.md
pkg/config/config.go
pkg/config/loader_test.go
pkg/config/nodeconfigs.go
pkg/config/testdata/talconfig.yaml
pkg/talos/nodeconfig.go

This adds a new `extraMachineCertSans` & `overrideExtraMachineCertSans` node & node group config option and deprecates the `additionalMachineCertSans` as a general option.
The `additionalMachineCertSans` field is not needed anymore since this can be easily done via node groups. Thus it is flagged as Deprecated in the documentation. JSON Schema and or [invopop/jsonschema](https://github.com/invopop/jsonschema) does not support deprecations. This could be usefull to flag in the schema
For the time being `additionalmachineCertSans` works as expected and `extraMachineCertSans` add on top of that. Both are appended to another (no duplication filtering for now).
I added two fields to the testdata to test if the new option works as expected. The `additionalMachineCertSans` was tested manually …

feat(config): add node `certSANs` and deprecate `additionalMachineCertSans`

---

pkg/config/validator.go
pkg/generate/config.go
pkg/substitute/pathsubst.go
pkg/substitute/pathsubst_test.go

When `extraManifests` is a list of relative paths, they were not being substituted to the absolute paths of `--config-file` flag.
`SubstituteRelativePaths` didn't work for `extraManifests` because the values doesn't need the `@` prefix before the file name.
Now, we just internally add the `@` prefix and call it a "special" case to simplify the code base.
This also fixes the case where absolute paths are given instead of relative paths.
Before this, they're joined to the directory of config file while now it should just be returned as if.
Fixes: https://github.com/budimanjojo/talhelper/issues/871

fix(loader): paths of `extraManifests` should be relative to config file

---

docs/docs/reference/configuration.md
example/talconfig.yaml
pkg/config/config.go
pkg/config/validate.go
pkg/config/validator.go
pkg/generate/config.go
pkg/talos/uservolumeconfig.go
pkg/talos/uservolumeconfig_test.go

Fixes: https://github.com/budimanjojo/talhelper/issues/941
- **feat(config): deprecate `machineDisks`**
- **feat(config): add `userVolumes` to generate `UserVolumeConfig`**

`MachineDisks` is deprecated, use `UserVolumeConfig` instead

---

docs/docs/reference/configuration.md
pkg/config/defaults.go
pkg/talos/nodeconfig_test.go
pkg/talos/schematic.go
pkg/talos/schematic_test.go

Fixes: https://github.com/budimanjojo/talhelper/issues/982
It seems like v1.10.0 the upstream `image-factory` gives out installer
url in new format. The baremetal platform before and after the change:
Before:
`factory.talos.dev/installer/abcdefg:v1.10.0`
After:
`factory.talos.dev/metal-installer/abcdefg:v1.10.0`
Although it seems like using the old url will pull the image just fine,
it's better if we follow the new url instead

feat(genconfig): reflect to the installer image url change

---

docs/docs/guides.md

Fixes: https://github.com/budimanjojo/talhelper/issues/1106

docs: clarify `sops` default config dir for MacOS
